//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineResSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightBooking_Info
    {
        public int booking_id { get; set; }
        public int cust_id { get; set; }
        public int journy_id { get; set; }
        public int schedule_id { get; set; }
        public string ticket_id { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual Ticketing_Info Ticketing_Info { get; set; }
    }
}
