//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineResSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticketing_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticketing_Info()
        {
            this.FlightBooking_Info = new HashSet<FlightBooking_Info>();
        }
    
        public string ticket_id { get; set; }
        public int journey_id { get; set; }
        public string @class { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightBooking_Info> FlightBooking_Info { get; set; }
        public virtual Journey Journey { get; set; }
    }
}
