//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineResSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int cust_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string country { get; set; }
        public string mobile { get; set; }
        public string email_addr { get; set; }
        public string passport_no { get; set; }
        public string misc_info { get; set; }
    
        public virtual Country Country1 { get; set; }
    }
}
